WebApplication7/WebApplication7/Models/Details.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Details
    {
        public Details()
        {
            this.Vehicles = new HashSet<Vehicles>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
        public string Articul { get; set; }
        public string Description { get; set; }
        public Nullable<int> Volume { get; set; }
        public string Size { get; set; }
        public string Consist { get; set; }
        public string Naznachenie { get; set; }
        public Nullable<int> Volume1 { get; set; }
        public string Discriminator { get; set; }
        public Nullable<int> Brends_Id { get; set; }
        public Nullable<int> Order_Id { get; set; }
        public Nullable<int> Tips_Id { get; set; }
    
        public virtual Markis Markis { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual Tips Tips { get; set; }
        public virtual ICollection<Vehicles> Vehicles { get; set; }
    }
}

WebApplication7/WebApplication7/Models/Markis.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Markis
    {
        public Markis()
        {
            this.Details = new HashSet<Details>();
            this.Vehicles = new HashSet<Vehicles>();
            this.Vehicles1 = new HashSet<Vehicles>();
            this.Vehicles2 = new HashSet<Vehicles>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Discriminator { get; set; }
    
        public virtual ICollection<Details> Details { get; set; }
        public virtual ICollection<Vehicles> Vehicles { get; set; }
        public virtual ICollection<Vehicles> Vehicles1 { get; set; }
        public virtual ICollection<Vehicles> Vehicles2 { get; set; }
    }
}

WebApplication7/WebApplication7/Controllers/MarkiController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication7.Classes;
using WebApplication7;

namespace WebApplication7.Controllers
{
    public class MarkiController : Controller
    {
        private CustomContext db = new CustomContext();

        // GET: /Marki/
        public ActionResult Index()
        {
            return View(db.Marks.ToList());
        }

        // GET: /Marki/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Marki marki = db.Marks.Find(id);
            if (marki == null)
            {
                return HttpNotFound();
            }
            return View(marki);
        }

        // GET: /Marki/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Marki/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,Name")] Marki marki)
        {
            if (ModelState.IsValid)
            {
                db.Marks.Add(marki);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(marki);
        }

        // GET: /Marki/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Marki marki = db.Marks.Find(id);
            if (marki == null)
            {
                return HttpNotFound();
            }
            return View(marki);
        }

        // POST: /Marki/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,Name")] Marki marki)
        {
            if (ModelState.IsValid)
            {
                db.Entry(marki).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(marki);
        }

        // GET: /Marki/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Marki marki = db.Marks.Find(id);
            if (marki == null)
            {
                return HttpNotFound();
            }
            return View(marki);
        }

        // POST: /Marki/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Marki marki = db.Marks.Find(id);
            db.Marks.Remove(marki);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication7/WebApplication7/Controllers/MotoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication7.Classes;
using WebApplication7;

namespace WebApplication7.Controllers
{
    public class MotoController : Controller
    {
        private CustomContext db = new CustomContext();
        private IEnumerable<Moto> mm;

        // GET: /Moto/
        public ActionResult Index(Marki_Moto M)
        {
            if(M.Id == 0)
            {
                return View(db.Motos.ToList());
            }
            mm = db.Motos.Where(n => n.Marks_Moto.Id == M.Id);
            return View(mm);
        }

        // GET: /Moto/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Moto moto = db.Motos.Find(id);
            if (moto == null)
            {
                return HttpNotFound();
            }
            return View(moto);
        }

        // GET: /Moto/Create
        public ActionResult Create()
        {
            ViewBag.id_ttype = new SelectList(db.Marks_Motos, "Id", "Name");
            
            return View();
        }

        // POST: /Moto/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name")] Moto moto, int id_ttype)
        {
            moto.Marks_Moto = db.Marks_Motos.First(n => n.Id == id_ttype);
            if (ModelState.IsValid)
            {
                db.Vehicles.Add(moto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            
            return View(moto);
        }

        // GET: /Moto/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Moto moto = db.Motos.Find(id);
            if (moto == null)
            {
                return HttpNotFound();
            }
            return View(moto);
        }

        // POST: /Moto/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,Name")] Moto moto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(moto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(moto);
        }

        // GET: /Moto/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Moto moto = db.Motos.Find(id);
            if (moto == null)
            {
                return HttpNotFound();
            }
            return View(moto);
        }

        // POST: /Moto/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Moto moto = db.Motos.Find(id);
            db.Vehicles.Remove(moto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication7/WebApplication7/Views/Marki/Create.cshtml
@model WebApplication7.Classes.Marki

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Marki</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication7/WebApplication7/Views/Marki/Delete.cshtml
@model WebApplication7.Classes.Marki

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Marki</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication7/WebApplication7/Views/Marki/Details.cshtml
@model WebApplication7.Classes.Marki

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Marki</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplication7/WebApplication7/Views/Marki/Edit.cshtml
@model WebApplication7.Classes.Marki

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Marki</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication7/WebApplication7/Views/Marki/Index.cshtml
@model IEnumerable<WebApplication7.Classes.Marki>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
    <input type="button" value="back" onclick="history.back()">
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(@item.Name, "Index", "Moto")
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>